# Generated by Django 5.2.4 on 2026-05-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='externalimg_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
