# Generated by Django 5.2.4 on 2026-05-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_externalimg_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='externalimg_url',
            new_name='external_img_url',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='img_url',
            new_name='upload_img_url',
        ),
    ]
