# Generated by Django 5.2.4 on 2026-05-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_externalimg_url_post_external_img_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='external_img_url',
            new_name='img_url',
        ),
    ]
