# Generated by Django 5.2.4 on 2026-05-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_external_img_url_post_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload_img_url',
        ),
        migrations.AddField(
            model_name='post',
            name='external_img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
