# Generated by Django 5.2.4 on 2026-05-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_upload_img_url_post_external_img_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_url',
            new_name='upload_img_url',
        ),
    ]
